name: expression
on: [push, pull_request, issues, workflow_dispatch]

jobs:
  using-expession-and-context:
    runs-on: ubuntu-latest
    steps:
      - name: expression
        id: exprs
        run: |
          echo ${{ 1 }}
          echo ${{'this is string'}}
          echo ${{ null }}
          echo ${{ true }}
          echo ${{true && false}}
          echo ${{true || (false && true) }}
      - name: econtarxt
        run: |
            echo '${{toJson(github)}}'
            echo '${{toJson(job)}}' 
    





